name: malinali
description: "French ↔ Pulaar translator (on-device MarianMT)."
publish_to: 'none'

version: 1.0.8+108

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.1
  args: ^2.7.0

  marian_flutter:
    path: ../marian_flutter
  language_picker_native_tongue:
    path: ../language_picker_native_tongue
  languages_dart: ^1.0.1
  dio: ^5.8.0

  vosk_flutter:
    git:
      url: https://github.com/malinali-app/vosk-flutter
      ref: bd5f53e
  permission_handler:
    git:
      url: https://github.com/weebi-com/flutter-permission-handler/
      ref: e4029c615a6e1fcb1ddfd7c66cf6f09324de3ab3
      path: permission_handler
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  record: ^7.1.1
  path: ^1.9.0
  archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.8
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/malinali_logo.jpg
    - assets/vosk-model-small-fr-0.22.zip
    - assets/fr-pul/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/malinali_logo.jpg"
  min_sdk_android: 24
  windows:
    generate: true
    image_path: "assets/malinali_logo.jpg"
  macos:
    generate: true
    image_path: "assets/malinali_logo.jpg"
  linux:
    generate: true
    image_path: "assets/malinali_logo.jpg"
  web:
    generate: true
    image_path: "assets/malinali_logo.jpg"
    background_color: "#ffffff"
    theme_color: "#ffffff"
